# Generated by Django 4.2.11 on 2024-03-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
    ]
